language: node_js # 언어는 node JS
node_js:
  - "12.13" # Node js 버전은 12.13
before_install: # 패키지를 다운로드 받기 전
  - npm install -g yarn # yarn을 글로벌로 설치한다
branches:
  only:
    - master # 마스터 브랜치에 Push 했을 때만 반영할 것이다.
    - dev
notifications: # 성공 실패 여부
  email:
    recipients:
      - museum114@naver.com 
      - dev.museum114@naver.com
